console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'
version = 3

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = '#81A1C1'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'
    foreground = '#6C6C6C'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_ahead_icon = '<#88C0D0>⇡ </>'
      branch_behind_icon = '<#88C0D0>⇣ </>'
      branch_icon = ''
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      github_icon = ''

[[blocks]]
  type = 'rprompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    foreground = '#A3BE8C'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '❯ '
    foreground = '#B48EAD'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  style = 'plain'
  template = '❯❯ '
